[package]
name = "try_match"
version = "0.2.3"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/yvt/try_match-rs"
description = """
An expression macro that does pattern matching and returns the result in `Result`.
"""
keywords = ["match", "pattern", "macro"]
categories = ["rust-patterns", "no-std"]

[features]
default = ["implicit_map", "std"]
implicit_map = ["proc-macro-hack", "try_match_inner"]
std = []

[dependencies]
proc-macro-hack = { version = "0.5.11", optional = true }
try_match_inner = { version = "= 0.3.0", path = "inner", optional = true }

[dev-dependencies]
if_rust_version = "1.0.0"

[workspace]
