[package]
name = "try_match"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/yvt/try_match-rs"
description = """
Attempt pattern matching and get the result in `Result`.
"""
keywords = ["match", "pattern", "macro"]
categories = ["rust-patterns", "no-std"]

[features]
default = ["implicit_map", "std"]
implicit_map = ["try_match_inner"]
std = []

[dependencies]
proc-macro-hack = "0.5.11"
try_match_inner = { version = "0.1.0", path = "inner", optional = true }

[workspace]
